// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxvIJokR5-RW2RrU-udGhac0bfzwYo5g',
    appId: '1:1015193375203:web:b2f8ecd0053d7984e0d0d6',
    messagingSenderId: '1015193375203',
    projectId: 'capstone-505a1',
    authDomain: 'capstone-505a1.firebaseapp.com',
    storageBucket: 'capstone-505a1.appspot.com',
    measurementId: 'G-B3BL4YGZPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdugpYGAYLKjzQIKygwWVkvwbTSzG7BMw',
    appId: '1:1015193375203:android:e259cd8e5149b9aae0d0d6',
    messagingSenderId: '1015193375203',
    projectId: 'capstone-505a1',
    storageBucket: 'capstone-505a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbGJifhpii_OXAOoxxi5X24BouVYczkao',
    appId: '1:1015193375203:ios:fc7443cc097eabf7e0d0d6',
    messagingSenderId: '1015193375203',
    projectId: 'capstone-505a1',
    storageBucket: 'capstone-505a1.appspot.com',
    iosClientId: '1015193375203-sstjrvj01v7b24s44pdp6lsv316g4uga.apps.googleusercontent.com',
    iosBundleId: 'com.example.capStoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbGJifhpii_OXAOoxxi5X24BouVYczkao',
    appId: '1:1015193375203:ios:b1a264df83000b32e0d0d6',
    messagingSenderId: '1015193375203',
    projectId: 'capstone-505a1',
    storageBucket: 'capstone-505a1.appspot.com',
    iosClientId: '1015193375203-2fvleq3lnoj7rfef3e5j0ea5sn2cevcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.capStoneProject.RunnerTests',
  );
}
